name: Run Cleanup Script and Create PR

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  run-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run cleanup script
        run: python cleanup.py

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create branch for changes
        run: |
          git checkout -b cleanup-changes
          git add .
          git commit -m "Run cleanup script"
          git push origin cleanup-changes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: cleanup-changes
          title: "Automated Cleanup Changes"
          body: "This PR contains changes made by the cleanup script."
